name: build and publish

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build
      run: make
